### ISSUE TITLE
Show pin icon on list to indicate the note is pinned

### ISSUE THREAD

**Issue by frvkl** [manogna4/obsidian-koncham-workspace#2]
It would be great, if the list reflects which notes in the list are actually pinned. Thank you.

**Comment by manogna4** [comment]
on my todo list already :)
having a pin icon show up is easy enough, but it takes up some space. would you be happy with a solution that doesn't take up space, like having a different colour instead?

**Comment by frvkl** [comment]
In that case. I would like to be able to style it using a CSS snippet. Adding a class suited for styling opportunities would be great. 👍

**Comment by manogna4** [comment]
@frvkl 
I noticed you closed the issue. Have you managed to solve it?
I have a version working on my pc that adds a class on pin. But it does so only on a subsequent change to workspace. I am new to js, so I don't know how to handle this. If you have, I am happy to merge that into the plugin
